---
env:
  TERM: alacritty-kieran

window:
  decorations: transparent
  dynamic_padding: true
  padding:
    y: 22
    x: 16

font:
  size: 12.0
  # use_thin_strokes: true
  draw_bold_text_with_bright_colors: true
  normal:
    family: "PragmataPro Liga"
    style: Regular
  bold:
    family: "PragmataPro Liga"
    style: Bold
  italic:
    family: "PragmataPro Liga"
    style: Italic

# challenger deep colors:
#   # Default colors
#   primary:
#     background: '0x1e1c31'
#     foreground: '0xcbe3e7'

#   # Normal colors
#   normal:
#     black:   '0x100e23'
#     red:     '0xff8080'
#     green:   '0x95ffa4'
#     yellow:  '0xffe9aa'
#     blue:    '0x91ddff'
#     magenta: '0xc991e1'
#     cyan:    '0xaaffe4'
#     white:   '0xcbe3e7'

#   # # Bright colors
#   bright:
#     black:   '0x565575'
#     red:     '0xff5458'
#     green:   '0x62d196'
#     yellow:  '0xffb378'
#     blue:    '0x65b2ff'
#     magenta: '0x906cff'
#     cyan:    '0x63f2f1'
#     white:   '0xa6b3cc'

# # TokyoNight Alacritty Colors
# colors:
#   # Default colors
#   primary:
#     background: '0x24283b'
#     foreground: '0xc0caf5'

#   # Normal colors
#   normal:
#     black:   '0x1D202F'
#     red:     '0xf7768e'
#     green:   '0x9ece6a'
#     yellow:  '0xe0af68'
#     blue:    '0x7aa2f7'
#     magenta: '0xbb9af7'
#     cyan:    '0x7dcfff'
#     white:   '0xa9b1d6'

#   # Bright colors
#   bright:
#     black:   '0x414868'
#     red:     '0xf7768e'
#     green:   '0x9ece6a'
#     yellow:  '0xe0af68'
#     blue:    '0x7aa2f7'
#     magenta: '0xbb9af7'
#     cyan:    '0x7dcfff'
#     white:   '0xc0caf5'

#   indexed_colors:
#     - { index: 16, color: '0xff9e64' }
#     - { index: 17, color: '0xdb4b4b' }

# # Nightfox colors
# colors:
#   # Default colors
#   primary:
#     background: '0x192330'
#     foreground: '0xcdcecf'
#   # Normal colors
#   normal:
#     black: '0x393b44'
#     red: '0xc94f6d'
#     green: '0x81b29a'
#     yellow: '0xdbc074'
#     blue: '0x719cd6'
#     magenta: '0x9d79d6'
#     cyan: '0x63cdcf'
#     white: '0xdfdfe0'
#   # Bright colors
#   bright:
#     black: '0x575860'
#     red: '0xd16983'
#     green: '0x8ebaa4'
#     yellow: '0xe0c989'
#     blue: '0x86abdc'
#     magenta: '0xbaa1e2'
#     cyan: '0x7ad4d6'
#     white: '0xe4e4e5'
#   indexed_colors:
#     - {index: 16, color: '0xf4a261'}
#     - {index: 17, color: '0xd67ad2'}

colors:
  # Default colors
  primary:
    background: '0x152528'
    foreground: '0xe6eaea'
  # Normal colors
  normal:
    black:   '0x2f3239'
    red:     '0xe85c51'
    green:   '0x7aa4a1'
    yellow:  '0xfda47f'
    blue:    '0x5a93aa'
    magenta: '0xad5c7c'
    cyan:    '0xa1cdd8'
    white:   '0xebebeb'
  # Bright colors
  bright:
    black:   '0x4e5157'
    red:     '0xeb746b'
    green:   '0x8eb2af'
    yellow:  '0xfdb292'
    blue:    '0x73a3b7'
    magenta: '0xb97490'
    cyan:    '0xafd4de'
    white:   '0xeeeeee'
  indexed_colors:
    - { index: 16, color: '0xff8349' }
    - { index: 17, color: '0xcb7985' }

key_bindings:
  - {key: Key3, mods: Alt, chars: "\x23"}
