---
version: "2"
region: eu
tunnels:
    7443:
        addr: 7443
        proto: tls
        hostname: ngrok.kieranbamforth.me
    7080:
        addr: 7080
        proto: http
        hostname: ngrok.kieranbamforth.me
        schemes:
            - http
    3000:
        addr: 3000
        proto: http
        hostname: ngrok.kieranbamforth.me
        schemes:
            - http
