env:
  TERM: xterm-256color

window:
  decorations: transparent
  dynamic_padding: true
  padding:
    y: 22
    x: 16

font:
  size: 14.0
  use_thin_strokes: true
  draw_bold_text_with_bright_colors: true
  normal:
    family: "PragmataPro Liga"
    style: Regular
  bold:
    family: "PragmataPro Liga"
    style: Bold
  italic:
    family: "PragmataPro Liga"
    style: Italic

colors:
  # Default colors
  primary:
    background: '0x1e1c31'
    foreground: '0xcbe3e7'

  # Normal colors
  normal:
    black:   '0x100e23'
    red:     '0xff8080'
    green:   '0x95ffa4'
    yellow:  '0xffe9aa'
    blue:    '0x91ddff'
    magenta: '0xc991e1'
    cyan:    '0xaaffe4'
    white:   '0xcbe3e7'

  # # Bright colors
  bright:
    black:   '0x565575'
    red:     '0xff5458'
    green:   '0x62d196'
    yellow:  '0xffb378'
    blue:    '0x65b2ff'
    magenta: '0x906cff'
    cyan:    '0x63f2f1'
    white:   '0xa6b3cc'

key_bindings:
  - { key: Key3, mods: Alt, chars: "\x23" }
