tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'jesseduffield/lazygit'
tap 'kieran-bamforth/homebrew-repo'
tap 'universal-ctags/universal-ctags'

cask '1password'
cask '1password-cli'
cask 'alfred2'
cask 'anki'
cask 'appzapper'
cask 'basictex'
cask 'crunch'
cask 'dash2'
cask 'docker'
cask 'dropbox'
cask 'eclipse-java'
cask 'firefox'
cask 'flux'
cask 'font-fira-code'
cask 'gas-mask'
cask 'google-chrome'
cask 'google-drive-file-stream'
cask 'imageoptim'
cask 'impactor'
cask 'intellij-idea-ce'
cask 'iterm2'
cask 'java'
cask 'karabiner-elements'
cask 'keystore-explorer'
cask 'kieran-bamforth/homebrew-repo/charles'
cask 'kieran-bamforth/homebrew-repo/focus'
cask 'kieran-bamforth/homebrew-repo/tunnelblick'
cask 'kitematic'
cask 'ksdiff'
cask 'launchcontrol'
cask 'microsoft-office'
cask 'mjolnir'
cask 'mysqlworkbench'
cask 'osxfuse'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'rowanj-gitx'
cask 'slack'
cask 'spotify'
cask 'suspicious-package'
cask 'tripmode'
cask 'vagrant'
cask 'virtualbox'
cask 'weka'

mas 'Apple Configurator 2', id: 1037126344
mas 'Boom 3D', id: 1233048948
mas 'JPEGmini Lite', id: 525742250
mas 'Kaleidoscope', id: 587512244
mas 'MindNode', id: 1289197285
mas 'OmniFocus', id: 1346203938
mas 'OmniGraffle', id: 711830901
mas 'Pocket', id: 568494494
mas 'Sketch', id: 852320343
mas 'Transmit', id: 403388562
mas 'Tweetbot', id: 557168941
mas 'WhatsApp Desktop', id: 1147396723
mas 'Xcode', id: 497799835
mas 'macOS server', id: 883878097

brew 'ansible'
brew 'ant'
brew 'antigen'
brew 'asciinema'
brew 'asdf'
brew 'autojump'
brew 'aws-shell'
brew 'awscli'
brew 'awslogs'
brew 'bat'
brew 'cmake'
brew 'coreutils'
brew 'diff-so-fancy'
brew 'direnv'
brew 'flake8'
brew 'fswatch'
brew 'fzf'
brew 'gawk'
brew 'git-secrets'
brew 'gnupg'
brew 'go-jira'
brew 'gradle'
brew 'graphviz'
brew 'gron'
brew 'http-server'
brew 'httpie'
brew 'hub'
brew 'imagemagick'
brew 'jid'
brew 'jq'
brew 'kieran-bamforth/homebrew-repo/awscli-wormhole-credentials'
brew 'kieran-bamforth/homebrew-repo/client-cert-proxy'
brew 'kieran-bamforth/homebrew-repo/csso'
brew 'kieran-bamforth/homebrew-repo/git-sweep'
brew 'kieran-bamforth/homebrew-repo/javascript-typescript-langserver'
brew 'kieran-bamforth/homebrew-repo/json-diff'
brew 'kieran-bamforth/homebrew-repo/lua'
brew 'kieran-bamforth/homebrew-repo/python-language-server'
brew 'kieran-bamforth/homebrew-repo/slack-cli'
brew 'kieran-bamforth/homebrew-repo/sqlmap'
brew 'kieran-bamforth/homebrew-repo/terminalizer'
brew 'kieran-bamforth/homebrew-repo/truffle-hog'
brew 'kieran-bamforth/homebrew-repo/uglifyjs'
brew 'lazygit'
brew 'libffi'
brew 'libyaml'
brew 'lolcat'
brew 'macvim', args: [ 'env-std', 'with-override-system-vim', 'with-python@2' ]
brew 'makefile2graph'
brew 'mas'
brew 'maven'
brew 'mycli'
brew 'ncdu'
brew 'node'
brew 'nss'
brew 'openssl'
brew 'pandoc'
brew 'plantuml'
brew 'poppler'
brew 'python'
brew 'python2'
brew 'ranger'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'rpm'
brew 'ruby'
brew 's3fs'
brew 'sbt'
brew 'sshfs'
brew 'svn'
brew 'the_silver_searcher'
brew 'tldr'
brew 'tmux'
brew 'tree'
brew 'universal-ctags/universal-ctags/universal-ctags', args: ['HEAD']
brew 'wget'
brew 'yarn'
brew 'zsh'
