tap 'Homebrew/homebrew-cask-fonts'
tap 'Homebrew/homebrew-cask-versions'
tap 'getantibody/tap'
tap 'heroku/brew'
tap 'kieran-bamforth/homebrew-repo'
tap 'universal-ctags/universal-ctags'
tap 'wagoodman/dive'

cask '1password'
cask '1password-cli'
cask 'alfred'
cask 'anki'
cask 'appzapper'
cask 'basictex'
cask 'browserstacklocal'
cask 'charles'
cask 'dash'
cask 'docker'
cask 'drawio'
cask 'dropbox'
cask 'firefox'
cask 'flux'
cask 'focus'
cask 'font-fira-code'
cask 'gas-mask'
cask 'google-drive-file-stream'
cask 'hammerspoon'
cask 'imageoptim'
cask 'impactor'
cask 'intellij-idea-ce'
cask 'iterm2'
cask 'java'
cask 'karabiner-elements'
cask 'keystore-explorer'
cask 'ksdiff'
cask 'launchcontrol'
cask 'metasploit'
cask 'microsoft-office'
cask 'ngrok'
cask 'nordvpn'
cask 'osxfuse'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'rowanj-gitx'
cask 'slack'
cask 'spotify'
cask 'suspicious-package'
cask 'tower'
cask 'tripmode'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'weka'
cask 'zoomus'
cask 'zotero'
cask 'zsa-wally'

mas 'Apple Configurator 2', id: 1037126344
mas 'Boom 3D', id: 1233048948
mas 'DaisyDisk', id: 411643860
mas 'Kaleidoscope', id: 587512244
mas 'Medis', id: 1063631769
mas 'MindNode', id: 1289197285
mas 'OmniFocus', id: 1346203938
mas 'Reeder', id: 1449412482
mas 'Transmit', id: 1436522307
mas 'Trello' , id: 1278508951
mas 'Tweetbot', id: 557168941
mas 'WhatsApp Desktop', id: 1147396723
mas 'Xcode', id: 497799835

brew 'amazon-ecs-cli'
brew 'ansible'
brew 'antibody'
brew 'asciinema'
brew 'asdf'
brew 'aws-shell'
brew 'aws-vault'
brew 'awscli'
brew 'awslogs'
brew 'black'
brew 'cmake'
brew 'coreutils'
brew 'diff-so-fancy'
brew 'direnv'
brew 'dive'
brew 'docker-credential-helper-ecr'
brew 'ffmepeg'
brew 'fzf'
brew 'gawk'
brew 'git-secrets'
brew 'github/gh/gh'
brew 'gnupg'
brew 'go-jira'
brew 'graphviz'
brew 'gron'
brew 'heroku'
brew 'httpie'
brew 'hub'
brew 'imagemagick'
brew 'jid'
brew 'jq'
brew 'kieran-bamforth/homebrew-repo/javascript-typescript-langserver'
brew 'kieran-bamforth/homebrew-repo/node-json-diff'
brew 'kieran-bamforth/homebrew-repo/node-json2yaml'
brew 'kieran-bamforth/homebrew-repo/python-git-sweep'
brew 'kieran-bamforth/homebrew-repo/python-language-server'
brew 'kieran-bamforth/homebrew-repo/python-prospector'
brew 'kieran-bamforth/homebrew-repo/redis-cli'
brew 'kieran-bamforth/homebrew-repo/terminalizer'
brew 'kieran-bamforth/homebrew-repo/truffle-hog'
brew 'kieran-bamforth/homebrew-repo/uglifyjs'
brew 'kieran-bamforth/homebrew-repo/up'
brew 'libffi'
brew 'libyaml'
brew 'lolcat'
brew 'luarocks'
brew 'macvim', args: [ 'env-std', 'with-override-system-vim', 'with-python@2' ]
brew 'makefile2graph'
brew 'mas'
brew 'mitmproxy'
brew 'mycli'
brew 'mypy'
brew 'ncdu'
brew 'node'
brew 'openssl'
brew 'pandoc'
brew 'pandoc-citeproc'
brew 'pinentry-mac'
brew 'plantuml'
brew 'poppler'
brew 'python'
brew 'readline'
brew 'ripgrep'
brew 'rpm'
brew 'ruby'
brew 's3fs'
brew 'sqlmap'
brew 'sshfs'
brew 'stunnel'
brew 'tldr'
brew 'tmate'
brew 'tmux'
brew 'trash'
brew 'tree'
brew 'universal-ctags/universal-ctags/universal-ctags', args: ['HEAD']
brew 'wget'
brew 'youtube-dl'
brew 'zsh'
