tap 'martido/homebrew-graph'

# brew 'rustup'
# cask 'alacritty'

cask '1password'
cask 'amethyst'
cask 'daisydisk'
cask 'docker'
cask 'drawio'
cask 'firefox'
cask 'google-drive-file-stream'
cask 'homebrew/cask-drivers/zsa-wally'
cask 'kaleidoscope'
cask 'karabiner-elements'
cask 'ksdiff'
cask 'lens'
cask 'maccy'
cask 'microsoft-office'
cask 'obsidian'
cask 'openvpn-connect'
cask 'slack'
cask 'spotify'
cask 'suspicious-package'
cask 'tower'
cask 'utm'
cask 'whatsapp'
cask 'zoom'
cask 'zotero'

mas 'Honey for Safari', id: 1472777122
mas 'Hush Nag Blocker', id: 1544743900
mas 'MindNode', id: 1289197285
mas 'OmniFocus', id: 1346203938
mas 'Reeder', id: 1449412482
mas 'Save to Pocket', id: 14773852133
mas 'Vimari', id: 1480933944

brew 'direnv'
brew 'dive'
brew 'docker-credential-helper'
brew 'doctl'
brew 'fswatch'
brew 'gh'
brew 'git'
brew 'jq'
brew 'kind'
brew 'kn'
brew 'koekeishiya/formulae/skhd'
brew 'kubectl'
brew 'nvim'
brew 'python@3.9'
brew 'reg'
brew 'rg'
brew 'skaffold'
brew 'tmux'
brew 'tree'
brew 'tree-sitter'
brew 'volta'
