tap 'martido/homebrew-graph'
tap 'koekeishiya/formulae'
tap 'heroku/brew'
tap 'lucagrulla/tap'
tap 'ankitpokhrel/jira-cli'
tap 'hashicorp/tap'

cask '1password'
cask 'alacritty'
cask 'amethyst'
cask 'aws-vault'
cask 'daisydisk'
cask 'firefox'
cask 'flipper'
cask 'gas-mask'
cask 'google-chrome'
cask 'google-drive'
cask 'karabiner-elements'
cask 'krisp'
cask 'launchcontrol'
cask 'maccy'
# cask 'microsoft-excel'
# cask 'microsoft-outlook'
# cask 'microsoft-powerpoint'
cask 'microsoft-teams'
# cask 'microsoft-word'
cask 'ngrok'
cask 'obsidian'
cask 'orbstack'
cask 'qbittorrent'
cask 'session-manager-plugin'
cask 'slack'
cask 'spotify'
cask 'suspicious-package'
cask 'tower'
cask 'visual-studio-code'
cask 'whatsapp'
cask 'zsa-wally'
cask 'zoom'

mas '1Password Safari', id: 1569813296
mas 'OmniFocus', id: 1346203938
mas 'Reeder', id: 1449412482

brew 'pkgxdev/made/pkgx'

brew 'dive'
brew 'doctl'
brew 'efm-langserver'
brew 'fswatch'
brew 'gitleaks'
brew 'hashicorp/tap/terraform-ls'
brew 'istioctl'
brew 'jira-cli'
brew 'koekeishiya/formulae/skhd'
brew 'lua-language-server'
brew 'nvim'
brew 'openssl'
brew 'sipcalc'
brew 'skaffold'
brew 'terraform'
brew 'tmux'

# Available in pkgx, keeping because of possible brew deps.
brew 'python@3.9'

# Available in pkgx, but keeping in brew as not user facing.
brew 'hadolint'
brew 'shellcheck'
brew 'shfmt'
brew 'tree-sitter'

# Available in pkgx, keeping because eval'd in shell so wanting perf.
brew "zoxide"
brew 'direnv'
brew 'rtx'

# Available in pkgx, keeping because wanted in git.
brew "gh"
brew "git"
brew "git-branchless"
brew "glab"

# Available in pkgx, needed for building parsers.
brew 'jq'

# Available in pkgx, needed in telescope.nvim
brew 'fd'
brew 'rg'
