auth_type: basic
board:
    id: 101
    name: SV board
    type: simple
epic:
    name: ""
    link: ""
installation: Cloud
issue:
    fields:
        custom:
            - name: Budget
              key: customfield_10190
              schema:
                datatype: number
            - name: Project start
              key: customfield_10230
              schema:
                datatype: string
            - name: Project target
              key: customfield_10231
              schema:
                datatype: string
            - name: Category
              key: customfield_10232
              schema:
                datatype: option
            - name: Category
              key: customfield_10111
              schema:
                datatype: option
            - name: Value
              key: customfield_10233
              schema:
                datatype: number
            - name: Company size
              key: customfield_10112
              schema:
                datatype: option
            - name: Effort
              key: customfield_10234
              schema:
                datatype: number
            - name: Website
              key: customfield_10113
              schema:
                datatype: string
            - name: Email
              key: customfield_10114
              schema:
                datatype: string
            - name: Idea short description
              key: customfield_10235
              schema:
                datatype: string
            - name: Confidence
              key: customfield_10346
              schema:
                datatype: number
            - name: Roadmap
              key: customfield_10225
              schema:
                datatype: option
            - name: Impact score
              key: customfield_10226
              schema:
                datatype: number
            - name: Customer segments
              key: customfield_10227
              schema:
                datatype: array
                items: option
            - name: Spec ready
              key: customfield_10228
              schema:
                datatype: number
            - name: Designs ready
              key: customfield_10229
              schema:
                datatype: number
            - name: Impact
              key: customfield_10223
              schema:
                datatype: number
            - name: Reach
              key: customfield_10345
              schema:
                datatype: number
            - name: Theme
              key: customfield_10224
              schema:
                datatype: array
                items: option
            - name: Atlassian project
              key: customfield_10040
              schema:
                datatype: string
            - name: Atlassian project status
              key: customfield_10041
              schema:
                datatype: string
            - name: Insights
              key: customfield_10042
              schema:
                datatype: number
            - name: Comments
              key: customfield_10043
              schema:
                datatype: number
            - name: Linked items
              key: customfield_10044
              schema:
                datatype: number
            - name: Delivery progress
              key: customfield_10045
              schema:
                datatype: string
            - name: Delivery status
              key: customfield_10046
              schema:
                datatype: string
            - name: Launch Priority
              key: customfield_10159
              schema:
                datatype: option
            - name: Idea archived by
              key: customfield_10038
              schema:
                datatype: array
                items: user
            - name: Idea archived on
              key: customfield_10039
              schema:
                datatype: datetime
            - name: Total Original
              key: customfield_10276
              schema:
                datatype: number
            - name: Design
              key: customfield_10035
              schema:
                datatype: array
                items: design.field.name
            - name: Total Remaining
              key: customfield_10277
              schema:
                datatype: number
            - name: Vulnerability
              key: customfield_10036
              schema:
                datatype: any
            - name: Remaining Tech
              key: customfield_10278
              schema:
                datatype: number
            - name: Original Design
              key: customfield_10157
              schema:
                datatype: number
            - name: Original Tech
              key: customfield_10158
              schema:
                datatype: number
            - name: Idea archived
              key: customfield_10037
              schema:
                datatype: option
            - name: Figma URL
              key: customfield_10312
              schema:
                datatype: string
            - name: Remaining Design
              key: customfield_10279
              schema:
                datatype: number
            - name: Goals
              key: customfield_10027
              schema:
                datatype: array
                items: Goals
            - name: Sprint
              key: customfield_10020
              schema:
                datatype: array
                items: json
            - name: Flagged
              key: customfield_10021
              schema:
                datatype: array
                items: option
            - name: Budget
              key: customfield_10379
              schema:
                datatype: number
            - name: Story point estimate
              key: customfield_10016
              schema:
                datatype: number
            - name: Issue colour
              key: customfield_10017
              schema:
                datatype: string
            - name: Rank
              key: customfield_10019
              schema:
                datatype: any
            - name: Start date
              key: customfield_10015
              schema:
                datatype: date
            - name: RICE Impact
              key: customfield_10240
              schema:
                datatype: number
            - name: RICE Effort
              key: customfield_10241
              schema:
                datatype: number
            - name: 'Subject '
              key: customfield_10120
              schema:
                datatype: string
            - name: Development
              key: customfield_10000
              schema:
                datatype: any
            - name: RICE Confidence
              key: customfield_10242
              schema:
                datatype: number
            - name: Student
              key: customfield_10121
              schema:
                datatype: string
            - name: Team
              key: customfield_10001
              schema:
                datatype: team
            - name: RICE Score
              key: customfield_10243
              schema:
                datatype: number
            - name: Tutor
              key: customfield_10122
              schema:
                datatype: string
            - name: Subject
              key: customfield_10123
              schema:
                datatype: string
            - name: Time
              key: customfield_10124
              schema:
                datatype: datetime
            - name: Phone number
              key: customfield_10115
              schema:
                datatype: string
            - name: Documents
              key: customfield_10237
              schema:
                datatype: string
            - name: Student
              key: customfield_10116
              schema:
                datatype: string
            - name: Product Area
              key: customfield_10238
              schema:
                datatype: array
                items: option
            - name: Tutor
              key: customfield_10117
              schema:
                datatype: string
            - name: RICE Reach
              key: customfield_10239
              schema:
                datatype: number
            - name: Session Time
              key: customfield_10118
              schema:
                datatype: string
            - name: Day of the week
              key: customfield_10119
              schema:
                datatype: option
    types:
        - id: "10070"
          name: Task
          handle: Task
          subtask: false
        - id: "10071"
          name: Bug
          handle: Bug
          subtask: false
        - id: "10072"
          name: Story
          handle: Story
          subtask: false
        - id: "10073"
          name: Epic
          handle: Epic
          subtask: false
        - id: "10074"
          name: Subtask
          handle: Subtask
          subtask: true
login: kieran@studia.io
project:
    key: SV
    type: next-gen
server: https://studia-team-gdndoc1i.atlassian.net
timezone: Europe/London
