abbreviate ADded Added
abbreviate ADding Adding
abbreviate UPdating Updating
abbreviate adding Adding
abbreviate ahve have
abbreviate andn and
abbreviate fixing Fixing
abbreviate fucntion function
abbreviate funciton function
abbreviate funcitons functions
abbreviate hsow show
abbreviate hte the
abbreviate htis this
abbreviate htose those
abbreviate implemment implement
abbreviate jst just
abbreviate maek make
abbreviate spome some
abbreviate teh the
abbreviate updating Updating
