#!/usr/bin/env bash
export TMUX_COLOR_ACCENT='#5a93aa'

export TMUX_COLOR_ALERT='#cbd9d8'
export TMUX_COLOR_BG='#0f1c1e'

export TMUX_COLOR_TAB_ACTIVE='#cbd9d8'
export TMUX_COLOR_TAB_ACTIVE_TEXT='#0f1c1e'

export TMUX_COLOR_TAB_INACTIVE='#0f1c1e'
export TMUX_COLOR_TAB_INACTIVE_TEXT='#587b7b'

export TMUX_RIGHT_STATUS_COLOR='#0f1c1e'
export TMUX_RIGHT_STATUS_TEXT_COLOR='#587b7b'

export TMUX_LEFT_STATUS_COLOR='#5a93aa'
export TMUX_LEFT_STATUS_TEXT_COLOR='#0f1c1e'

export TMUX_MESSAGE_COMMAND_COLOR='#cbd9d8'
export TMUX_MESSAGE_COMMAND_TEXT_COLOR='#0f1c1e'
