[tools]
node = "20"
terraform = "1.7.5"
terragrunt = "0.55.5"

[env]
JIRA_CONFIG_FILE = "${XDG_CONFIG_HOME}/.jira/.config.jd.yml"
GH_REQUIRED_ACCOUNT = "Kieran-OHara_JDPLC"
_.file = [{ path = ".env", redact = true }, ".env.local"]

[settings]
env_shell_expand = true
