#!/bin/bash -e

# If we're already inside an aws-vault subshell, AWS credentials are in the
# environment. Re-invoking aws-vault would nest and fail.
if [ -n "$AWS_VAULT" ]; then
  exec docker run --rm \
    -e AWS_REGION \
    -e AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY \
    -e AWS_SESSION_TOKEN \
    -e AWS_SECURITY_TOKEN \
    -e AWS_PAGER="" \
    -v "${AWS_CONFIG_FILE:-$HOME/.config/aws/config}:/root/.aws/config:ro" \
    -v "$(pwd)":/workdir \
    -w /workdir \
    kieranbamforth/aws-cli:latest "$@"
fi

aws-vault exec ${AWS_PROFILE:=kieran} -- docker run --rm \
  -e AWS_REGION \
  -e AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY \
  -e AWS_SESSION_TOKEN \
  -e AWS_SECURITY_TOKEN \
  -e AWS_PAGER="" \
  -v "${AWS_CONFIG_FILE:-$HOME/.config/aws/config}:/root/.aws/config:ro" \
  -v "$(pwd)":/workdir \
  -w /workdir \
  kieranbamforth/aws-cli:latest "$@"
