#!/bin/zsh -li

if [ "$1" = "mw" ]; then
  /opt/homebrew/bin/jira issue list \
    --jql 'project = MW AND (fixVersion in unreleasedVersions() OR fixVersion is EMPTY) AND status IN ("Ready for Development", "In Progress", "Investigating", "Peer review", "ready for testing", "In Testing", "Ready for Deployment", "Documenting") AND priority IN (Highest, High)' \
    --order-by Rank \
    --reverse \
    "${@:2}"
else
  /opt/homebrew/bin/jira "$@"
fi
