#!/bin/bash -xe
NAMESPACE="$1"
URI="$2"
REPO_NAME=$(basename "$URI")

DIR=config/nvim/pack/$NAMESPACE/start/"$REPO_NAME"
if [ ! -d "$DIR" ]; then
  git submodule add --name "$REPO_NAME" --force https://github.com/"$URI" "$DIR"
  # Index the help docs.
  nvim -c ':helptags ALL' -c 'qa'
fi
