---
version: 2
root-markers:
  - .git/
  - package.json
log-level: 5
log-file: /Users/kieranohara/.cache/nvim/efm-langserver.log

lint-debounce: 1s
tools:

  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: 'hadolint'
    lint-formats:
      - '%f:%l %m'

  javascript-eslint: &javascript-eslint
    lint-command: |
      'npx eslint_d -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-source: 'eslint_d'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"

  lua-lua-format: &lua-lua-format
    format-command: 'lua-format -i'
    format-stdin: true

  lua-luacheck: &lua-luacheck
    lint-command: 'luacheck --formatter visual_studio --filename ${INPUT} -'
    lint-source: 'luacheck'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c) : %tarning %m"
      - "%f(%l,%c) : %rror %m"

  markdown-markdownlint: &markdown-markdownlint
    lint-command: 'markdownlint -s'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%f:%l %m'
      - '%f:%l:%c %m'
      - '%f: %l: %m'

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -filename ${INPUT} -i 2 -'
    format-stdin: true

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-source: 'yamllint'
    lint-ignore-exit-code: true
    lint-stdin: true

languages:

  dockerfile:
    - <<: *dockerfile-hadolint

  javascript:
    - <<: *javascript-eslint

  lua:
    - <<: *lua-lua-format
    - <<: *lua-luacheck

  markdown:
    - <<: *markdown-markdownlint

  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt

  yaml:
    - <<: *yaml-yamllint
