---
version: 2
root-markers:
  - .git/
  - package.json
log-level: 5
log-file: /Users/kieranohara/.local/state/efm-langserver/logs/lua.log

lint-debounce: 1s
tools:

  lua-luacheck: &lua-luacheck
    lint-command: 'luacheck --formatter visual_studio --filename ${INPUT} -'
    lint-source: 'luacheck'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c) : %tarning %m"
      - "%f(%l,%c) : %rror %m"

  format: &format
    format-command: 'lua-format -i'
    format-stdin: true

languages:

  lua:
    - <<: *lua-luacheck
    - <<: *format
