name: Pack and Publish
on:
  push:
    branches:
      - main
jobs:
  pack_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          make SHELL=/bin/bash dependencies/node_modules.zip
          echo "::set-output name=package_path::dependencies/node_modules.zip"
          ls dependencies
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "0.0.1"
          files: |
            dependencies/node_modules.zip
